#!/bin/bash
source "$CONFIG_DIR/colors.sh"
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar \
  position=top \
  height=36 \
  blur_radius=0 \
  color=$BAR_COLOR \
  corner_radius=5 \
  margin=0 \
  padding_left=10 \
  padding_right=10 \
  y_offset=0 # offset from top of screen

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=0
  icon.font="Hack Nerd Font:Bold:16.0"
  icon.color=$WHITE
  icon.padding_left=10
  icon.padding_right=0
  label.padding_left=5
  label.padding_right=10

  label.font="Hack Nerd Font:Bold:15.0"
  label.color=$WHITE
  background.corner_radius=0 
  background.height=32
)

# Apply default values properly
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.


##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

           # --set logo icon.color=0xff9dd274 \
## Logo 


sketchybar --add item front_app_icon left \
           --set front_app_icon \
           background.height=28 \
           background.color=transparent \
           background.corner_radius=5 \
           label.drawing=on \
           label.color=0xff000000 \
           label.padding_right=4 \
           label.padding_left=3 \
           icon.font="sketchybar-app-font:Regular:18.0" \
           icon.color=0xFF97BCFE \
           icon.drawing=on script="$PLUGIN_DIR/front_app_icon.sh" \
           --subscribe front_app_icon front_app_switched \

# react logo icon=􀬚
# sketchybar --add item logo left \
#            --set logo icon= \
#            --set logo icon.color=$WHITE \
#            --set logo background.drawing=on \
#            --set logo background.color=$BAR_COLOR \
#            --set logo background.corner_radius=5 \
#            --set logo background.height=30 \
#            --set logo label.drawing=on \
#            --set logo label.padding_right=5 \
#            --set logo background.border_width=0 \
#            --set logo background.border_color=0xff070707 \
#            --set logo background.border_position=all
#


## Aerospace Workspaces
sketchybar --add event aerospace_workspace_change

# Define the appearance of the bracket
workspace_bracket=(
  background.color=transparent
  background.border_color=$BORDER_COLOR
  background.border_width=0
  background.corner_radius=5
  background.padding_left=0
  background.padding_right=0
)

# Add workspace items
for sid in $(aerospace list-workspaces --monitor all --empty no); do
  sketchybar --add item space.$sid left \
             --subscribe space.$sid aerospace_workspace_change \
             --set space.$sid \
                   background.drawing=off \
                   background.color=transparent \
                   background.corner_radius=3 \
                   background.height=24 \
                   background.drawing=off \
                   label.color=$GREY \
                   label.padding_right=15 \
                   label="$sid" \
                   padding_left=5 \
                   click_script="aerospace workspace $sid" \
                   script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Create a bracket to group the workspace items
sketchybar --add bracket workspace_bracket '/space\..*/' \
           --set workspace_bracket "${workspace_bracket[@]}"


## Front App
sketchybar --add item front_app left \
           --set front_app \
           background.drawing=on \
           background.color=transparent \
           background.corner_radius=5 \
           background.height=32 \
           background.border_width=0 \
           background.border_color=$BORDER_COLOR \
           background.border_position=all \
           label.drawing=off \
           label.color=0xffffffff \
           label.padding_left=10 \
           icon.font="sketchybar-app-font:Regular:16.0" \
           icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched \


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# sketchybar --add item clock right \
#            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change


# Define the appearance of the bracket
status_bracket=(
  background.color=$BAR_COLOR
  background.border_color=$BORDER_COLOR
  background.border_width=0
  background.corner_radius=5
  background.padding_left=5
  background.padding_right=5
)

# Add the calendar item
sketchybar --add item calendar right \
           --set calendar icon=􀧞 \
                          update_freq=30 \
                          script="$PLUGIN_DIR/calendar.sh"

# Add the battery item
sketchybar --add item battery right \
           --set battery update_freq=120 \
                          script="$PLUGIN_DIR/examples/battery.sh" \
                          background.padding_left=-15 \
           --subscribe battery system_woke power_source_change

# Add the WiFi alias
sketchybar --add alias "Control Center,WiFi" right \
           --set "Control Center,WiFi" background.padding_left=5

# Create a bracket to group the items
sketchybar --add bracket status_bracket calendar battery "Control Center,WiFi" \
           --set status_bracket "${status_bracket[@]}"
# brackets 
# sketchybar --add bracket spaces logo front_app calendar \ 
#            --set spaces background.color=$ITEM_BG_COLOR \
#                       background.height=20 background.corner_radius=5

# sketchybar --add bracket main_bracket logo front_app \
#   --set main_bracket \
#         background.color=$BAR_COLOR \
#         background.corner_radius=4 \
#         background.height=24

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
